name: Build and deploy Node.js and React apps to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build backend
        run: |
          cd server
          npm install
          npm run build --if-present
          npm run test --if-present || echo "Skipping tests..."

      - name: Zip artifact for deployment
        run: |
          cd server
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_53ABBE666E6547C3B6AC7AC965D05361 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0A363A5D8AC44DDB8373C964CC85CA45 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_04529C6B8938482EADC61C0397F46929 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'localbackendtestmongodb'
          slot-name: 'Production'
          package: .

  build-deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: 'Production'
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build frontend
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy frontend to Azure Static Web Apps
        id: deploy-frontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_SEA_01E9CFE1E}}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "client/build"
          output_location: ""

